<a href="https://colab.research.google.com/github/mattaugustt/Computa-o-2-UFRJ-/blob/main/Pratica_7_comp_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Nome: <br>
Matheus Augusto de Souza. <br>
<br>
##DRE: <br>
118164136


In [ ]:
import numpy as np

#1 - Vamos resolver o seguinte sistema de equações lineares utilizando o método de eliminação gaussiana e a biblioteca NumPy: <br>
2x + y - z = 8 <br>
-3x - y + 2 = -11 <br>
-2x + y + 2z = -3


In [ ]:
#montando a matriz:
linha1 = [2,1,-1,8]
linha2 = [-3,-1,2,-11]
linha3 = [-2,1,2,-3]
x = np.array([linha1, linha2, linha3])
x
#linha 1 = x[0]
#linha 2 = x[1]
#linha 3 = x[2]

array([[  2,   1,  -1,   8],
       [ -3,  -1,   2, -11],
       [ -2,   1,   2,  -3]])

a) Linha2 = Linha2 + 3/2.Linha1

In [ ]:
x[1] = (x[1] + (x[0]*3/2))
x

array([[ 2,  1, -1,  8],
       [ 0,  0,  0,  1],
       [-2,  1,  2, -3]])

b) Linha3 = Linha3 + Linha1

In [ ]:
x[2] = x[2] + x[0]
x

array([[ 2,  1, -1,  8],
       [ 0,  0,  0,  1],
       [ 0,  2,  1,  5]])

c)Linha3 = Linha3 - 4Linha2

In [ ]:
x[2] = x[2] - (4*x[1])
x

array([[ 2,  1, -1,  8],
       [ 0,  0,  0,  1],
       [ 0,  2,  1,  1]])

d) Linha2 = Linha2 + 1/2.Linha3

In [ ]:
x[1] = x[1] + (x[2]*1/2)
x

array([[ 2,  1, -1,  8],
       [ 0,  1,  0,  1],
       [ 0,  2,  1,  1]])

e) Linha1 = Linha1 - Linha3

In [ ]:
x[0] = x[0] - x[2]
x

array([[ 2, -1, -2,  7],
       [ 0,  1,  0,  1],
       [ 0,  2,  1,  1]])

f) Linha2 = 2Linha2

In [ ]:
x[1] = 2*x[1]
x

array([[ 2, -1, -2,  7],
       [ 0,  2,  0,  2],
       [ 0,  2,  1,  1]])

g) Linha3 = -Linha3

In [ ]:
x[2] = -x[2]
x

array([[ 2, -1, -2,  7],
       [ 0,  2,  0,  2],
       [ 0, -2, -1, -1]])

h) Linha1 = Linha1 - Linha2

In [ ]:
x[0] = x[0] - x[1]
x

array([[ 2, -3, -2,  5],
       [ 0,  2,  0,  2],
       [ 0, -2, -1, -1]])

i) Linha1 = 1/2.Linha1

In [ ]:
x[0] = x[0]*1/2
x

array([[ 1, -1, -1,  2],
       [ 0,  2,  0,  2],
       [ 0, -2, -1, -1]])

Resultado esperado: <br>
[1, 0, 0, 2] <br>
[0, 1, 0, 3] <br>
[0, 0, 1, -1]

Como através dessas linhas de execução não obtivemos o resultado correto, vamos fazer através do método matemático.


In [ ]:
#montando a matriz:
linha1 = [2,1,-1,8]
linha3 = [-3,-1,2,-11]
linha2 = [-2,1,2,-3] #mudando a ordem para facilitar
x = np.array([linha1, linha2, linha3])
x
#linha 1 = x[0]
#linha 2 = x[1]
#linha 3 = x[2]

array([[  2,   1,  -1,   8],
       [ -2,   1,   2,  -3],
       [ -3,  -1,   2, -11]])

In [ ]:
#pivô linha 1 = 2, logo
#para zerar o x da segunda linha:
x[1] = x[0] + x[1]
x

array([[  2,   1,  -1,   8],
       [  0,   2,   1,   5],
       [ -3,  -1,   2, -11]])

In [ ]:
#para zerar o x da terceira linha:
x[2] = 3*x[0] + 2*x[2]
x

array([[ 2,  1, -1,  8],
       [ 0,  2,  1,  5],
       [ 0,  1,  1,  2]])

In [ ]:
#pivô da segunda linha = 2, logo
#para zerar o y da terceira linha:
x[2] = x[1] - 2*x[2]
x

array([[ 2,  1, -1,  8],
       [ 0,  2,  1,  5],
       [ 0,  0, -1,  1]])

In [ ]:
#agora devemos encontrar os valores que satisfassam as funções:
#-1.z = 1 => z = -1.
x[2][2] = x[2][2]*(-1)
x[2][3] = -1
x

array([[ 2,  1, -1,  8],
       [ 0,  2,  1,  5],
       [ 0,  0,  1, -1]])

In [ ]:
#para y: 2y + 1.-1 = 5 => y = 3
x[1][1] = x[1][1]/2
x[1][2] = x[1][2]-1
x[1][3] = 3
x

array([[ 2,  1, -1,  8],
       [ 0,  1,  0,  3],
       [ 0,  0,  1, -1]])

In [ ]:
#para x: 2x + 1.3 + -1.-1 = 8 => x = 2
x[0][0] = x[0][0]/2
x[0][1] = x[0][1] - 1
x[0][2] = x[0][2] + 1
x[0][3] = 2
x

array([[ 1,  0,  0,  2],
       [ 0,  1,  0,  3],
       [ 0,  0,  1, -1]])

#2 - Faça uma função que dado um intervalo fechado [a, b] e um número de pontos n, retorna o array x, formado pelos n pontos obtidos a partir do intervalo [a, b] e y é o array onde yi = x²i − 9.



In [ ]:
def intervalo(x, n):
  #recebe uma lista com dois valores, sendo [a,b] e um número inteiro de pontos
  a = x[0]
  b = x[1]
  intervalo = np.linspace(a,b,n)
  y = intervalo**2 - 9
  print(f'Array x: {intervalo}, \nArray y: {y}')



In [ ]:
intervalo([0,10],8)

Array x: [ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ], 
Array y: [-9.         -6.95918367 -0.83673469  9.36734694 23.65306122 42.02040816
 64.46938776 91.        ]


#3 - Considere a expressão polinomial:
p(x) = a0 + a1.x + a2.x² + ... + an.x^n = Somatório de an.x^n, de n = 0 até N.
<br>

Escreva uma função que utilize arrays e operações em arrays NumPy para calcular tal polinômio, sem usar laços. <br>
Dica: use np.cumprod().


In [ ]:
import numpy as np

def polinomio(n):
  arr = np.array(range(0,n+1))
  resultado = np.cumprod(x**arr)
  return resultado


In [ ]:
polinomio(10)

array([                  1,                   1,                   4,
                       108,               27648,            86400000,
             4031078400000, 3319766398771200000, -907465429310504960,
       2649120435010011136, 7504122879106088960])